import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { intakeMidi, intake, newWorkspace, analyzeWorkspace, invalidate, importWorkspace, recordReview, REVIEW_NAMES } from '../web/model.mjs';
import {
  MAX_MIDI_BYTES, MIDI_SOURCE_FORMAT, decodeSourceBytes, encodeSourceBytes,
  isRawMidiAsset, looksLikeMidi, verifySourceBytes,
} from '../web/midi-source.mjs';
import { createSourceRequestLedger, SOURCE_REQUEST_PROJECT_CHANGED, STALE_SOURCE_REQUEST } from '../web/source-requests.mjs';
import { f } from '../backend/mml/index.mjs';
import { mergeCanonicalProjects } from '../backend/canonical/merge.mjs';
import * as fixtures from './fixtures/midi-fixtures.mjs';

// Studio Web Raw MIDI transport.
//
// The backend suites already prove what `ingestMIDI` decodes. What is unproven
// until here is that the browser path reaches that decoder with the exact bytes
// the user chose, that nothing between the file picker and the Canonical
// project reinterprets them, and that what is written to storage decodes back
// to the same sequence. Every fixture is synthetic and generated by this
// repository.

const asset = (name, bytes, options = {}) => intakeMidi({ name, bytes, id: options.id ?? 'web-midi', authority: options.authority });
const nodeDigest = bytes => createHash('sha256').update(Buffer.from(bytes)).digest('hex');

// ─── byte-exact transport ───────────────────────────────────────────────────

test('the persistence encoding is byte-exact for every byte value', () => {
  const every = new Uint8Array(256).map((_, index) => index);
  assert.deepEqual([...decodeSourceBytes(encodeSourceBytes(every))], [...every]);

  // Lengths around the base64 padding boundaries, plus a body of arbitrary
  // bytes: a UTF-8 round trip would replace the invalid sequences in here.
  for (const length of [0, 1, 2, 3, 4, 5, 255, 1024, 4097]) {
    const bytes = new Uint8Array(length).map((_, index) => (index * 97 + 13) & 0xff);
    const back = decodeSourceBytes(encodeSourceBytes(bytes));
    assert.deepEqual([...back], [...bytes], `length ${length} must survive`);
    assert.equal(nodeDigest(back), nodeDigest(bytes));
  }
});

test('a malformed persistence encoding is refused rather than silently repaired', () => {
  for (const bad of ['not base64!', 'TVRoZA', 'TVRo ZA==', null, undefined, 42]) {
    assert.throws(() => decodeSourceBytes(bad), /SOURCE_BYTES_UNREADABLE/);
  }
});

test('the source digest is taken over exactly the bytes that were parsed', () => {
  const bytes = fixtures.format1();
  const result = asset('format1.mid', bytes);
  assert.equal(result.source.sha256, nodeDigest(bytes));
  assert.equal(result.source.byteLength, bytes.length);
  assert.equal(result.project.sources[0].sha256, result.source.sha256);
  assert.deepEqual([...decodeSourceBytes(result.source.bytesBase64)], [...bytes]);
  assert.equal(verifySourceBytes(result).verified, true);
});

test('an ArrayBuffer and a subarray view over the same bytes ingest identically', () => {
  const bytes = fixtures.format0();
  const padded = new Uint8Array(bytes.length + 8);
  padded.set(bytes, 8);
  const view = padded.subarray(8);

  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  const fromBuffer = asset('a.mid', buffer);
  const fromView = asset('a.mid', view);

  assert.equal(fromBuffer.source.sha256, nodeDigest(bytes));
  assert.equal(fromView.source.sha256, fromBuffer.source.sha256);
  assert.equal(JSON.stringify(fromView.project), JSON.stringify(fromBuffer.project));
  // Structured clone is the Worker boundary's copy semantics: the page's own
  // buffer is never transferred, so it is still readable afterwards.
  assert.equal(buffer.byteLength, bytes.length, 'the page copy must not be detached');
});

test('a Worker round trip preserves the asset and its exact rational timing', () => {
  const result = asset('rational.mid', fixtures.rationalTiming());
  const starts = result.project.events.map(event => event.start);
  // 0, 1/3, 2/3, 1, 13/12, 29/24 -- values no float projection reproduces.
  assert.deepEqual(starts, ['0', '1/3', '2/3', '1', '13/12', '29/24']);
  assert.deepEqual(result.project.events.map(event => event.end), ['1/3', '2/3', '1', '13/12', '29/24', '2']);

  for (const transported of [structuredClone(result), JSON.parse(JSON.stringify(result))]) {
    assert.deepEqual(transported.project.events.map(event => event.start), starts);
    assert.equal(transported.source.sha256, result.source.sha256);
    assert.equal(verifySourceBytes(transported).verified, true);
    // Exact rationals, not decimal approximations of them.
    assert.equal(f(transported.project.events[1].start).cmp(f('1/3')), 0);
    assert.equal(f(transported.project.events[5].start).cmp(f('29/24')), 0);
  }
});

test('accumulated thirds stay exact over many bars', () => {
  const notes = [];
  for (let index = 0; index < 600; index++) notes.push([0, 60 + (index % 12), index * (fixtures.PPQ / 3), (index + 1) * (fixtures.PPQ / 3)]);
  const bytes = fixtures.buildMidi({ format: 0, division: fixtures.PPQ, tracks: [fixtures.buildTrack(fixtures.notesToEntries(notes))] });
  const result = asset('thirds.mid', bytes);
  const last = structuredClone(result).project.events.at(-1);
  assert.equal(last.end, '200');
  assert.equal(f(last.start).cmp(f('599/3')), 0);
});

// ─── G11-A intake invariants, reached through the Web adapter ───────────────

test('SMF format 0 and format 1 both reach the Canonical IR', () => {
  const zero = asset('zero.mid', fixtures.format0());
  assert.equal(zero.midi.smfFormat, 0);
  assert.equal(zero.midi.division.type, 'ppq');
  assert.equal(zero.project.events.length, 3);
  assert.equal(zero.project.tempoEvents.length, 1);
  assert.equal(zero.project.meterEvents.length, 1);
  assert.equal(zero.complete, true);

  const one = asset('one.mid', fixtures.format1());
  assert.equal(one.midi.smfFormat, 1);
  assert.equal(one.midi.trackCount, 3);
  assert.equal(one.project.events.length, 5);
  assert.equal(one.complete, true);
  // Track and channel together identify the independent line.
  assert.deepEqual(one.midi.sourceVoices, ['track:1/channel:0', 'track:2/channel:1']);
});

test('a legal blank track name does not destroy the ingest', () => {
  const result = asset('blank.mid', fixtures.blankTrackName());
  assert.equal(result.complete, true);
  assert.equal(result.project.events.length, 2);
  // Preserved verbatim as evidence, but never promoted to a project title.
  assert.equal(result.midi.tracks[0].name, '   ');
  assert.equal(result.project.title, 'blank.mid');
});

test('running status and note-on velocity 0 releases decode as releases, not attacks', () => {
  const running = asset('running.mid', fixtures.runningStatus());
  assert.equal(running.complete, true);
  assert.equal(running.project.events.length, 2);
  assert.deepEqual(running.project.events.map(event => [event.pitch, event.start, event.end]), [[60, '0', '1'], [62, '1', '2']]);
  assert.equal(running.project.events[0].metadata.releaseEncoding, 'note-on-velocity-0');

  const velocityZero = asset('vz.mid', fixtures.velocityZeroReleases());
  assert.equal(velocityZero.project.events.length, 2);
  for (const event of velocityZero.project.events) assert.equal(event.metadata.releaseEncoding, 'note-on-velocity-0');
});

test('the program in force at each attack is the one recorded', () => {
  const result = asset('program.mid', fixtures.programAtNoteOn());
  const [first, second] = result.project.events;
  assert.equal(first.metadata.program, 0);
  assert.equal(second.metadata.program, 73, 'a later program change must not rewrite an earlier note');
});

test('same-pitch restrikes keep both notes and are reported for review', () => {
  const result = asset('overlap.mid', fixtures.overlappingSamePitch());
  assert.equal(result.project.events.length, 2);
  assert.equal(result.complete, true, 'a restrike is a warning about the source, not unsupported material');
  assert.ok(result.warnings.some(item => item.code === 'RESTRUCK_BEFORE_RELEASE'));
  assert.equal(result.midi.warningCounts.RESTRUCK_BEFORE_RELEASE, 1);
});

test('tempo and meter maps survive with their exact source integers', () => {
  const result = asset('zero.mid', fixtures.format0());
  assert.equal(result.project.tempoEvents[0].bpm, 120);
  assert.equal(result.project.tempoEvents[0].metadata.microsecondsPerQuarter, 500000);
  assert.equal(result.project.meterEvents[0].numerator, 4);
  assert.equal(result.project.meterEvents[0].denominator, 4);
  assert.equal(result.midi.hasTempo, true);
  assert.equal(result.midi.hasMeter, true);
});

// ─── fail-closed ────────────────────────────────────────────────────────────

test('bytes that are not a Standard MIDI File fail visibly', () => {
  assert.throws(() => asset('lying-name.mid', fixtures.notMidiAtAll()), /MThd/);
  assert.throws(() => asset('short.mid', fixtures.truncatedHeader()), /too short/);
  assert.throws(() => asset('empty.mid', new Uint8Array(0)), /UNSUPPORTED: empty MIDI file/);
  assert.throws(() => asset('huge.mid', new Uint8Array(MAX_MIDI_BYTES + 1)), /UNSUPPORTED: MIDI file exceeds/);
});

test('partially damaged files keep their evidence and stay incomplete', () => {
  for (const [name, bytes, code] of [
    ['truncated.mid', fixtures.truncatedTrack(), 'TRACK_TRUNCATED'],
    ['unknown-chunk.mid', fixtures.badChunkType(), 'TRACK_COUNT_MISMATCH'],
    ['no-status.mid', fixtures.runningStatusWithoutStatus(), 'RUNNING_STATUS_WITHOUT_STATUS'],
    ['smpte.mid', fixtures.smpteDivision(), 'SMPTE_DIVISION_NOT_MUSICAL_TIME'],
    ['format2.mid', fixtures.format2(), 'FORMAT_2_INDEPENDENT_SEQUENCES'],
    ['after-eot.mid', fixtures.dataAfterEndOfTrack(), 'DATA_AFTER_END_OF_TRACK'],
  ]) {
    const result = asset(name, bytes);
    assert.equal(result.complete, false, `${name} must not be reported complete`);
    assert.ok(result.unsupported.some(item => item.code === code), `${name} must retain ${code}`);
    assert.ok(Object.keys(result.midi.unsupportedCounts).includes(code));
    // The bytes are still exactly what was read, damage included.
    assert.deepEqual([...decodeSourceBytes(result.source.bytesBase64)], [...bytes]);
  }
});

test('caller metadata cannot raise a backend completeness verdict', () => {
  const damaged = asset('truncated.mid', fixtures.truncatedTrack());
  assert.equal(damaged.complete, false);

  // Whatever a restored or imported record claims, the analysis reads the
  // evidence, not the claim.
  const laundered = structuredClone(damaged);
  laundered.complete = true;
  laundered.unsupported = [];
  laundered.project.metadata.sourceComplete = true;

  let workspace = { ...newWorkspace(), title: 'fixture', settings: { meterText: '0 4/4', recording: 'synthetic', offset: '0', end: '2', audioRequired: 'no', preview: 'none' } };
  workspace.assets.candidate = laundered;
  workspace.assets.baseline = laundered;
  for (const name of REVIEW_NAMES) workspace = recordReview(workspace, name, 'reviewed', 'synthetic');

  const report = analyzeWorkspace(workspace);
  const entry = report.rawMidi[0];
  assert.equal(entry.claimedComplete, true, 'the record still says what it says');
  assert.equal(entry.complete, false, 'but the verdict comes from re-reading the bytes');
  assert.equal(entry.integrity.verified, false);
  assert.ok(entry.integrity.reasons.includes('STORED_COMPLETENESS_DOES_NOT_MATCH_SOURCE_BYTES'));
  assert.ok(entry.integrity.reasons.includes('STORED_UNSUPPORTED_EVIDENCE_DOES_NOT_MATCH_SOURCE_BYTES'));
  assert.equal(entry.unsupported.some(item => item.code === 'TRACK_TRUNCATED'), true, 'the erased evidence is restored to the report');

  assert.equal(report.gates.rawMidiSource.status, 'UNSUPPORTED');
  assert.equal(report.gates.source.status, 'UNSUPPORTED', 'a recorded source review cannot stand in for the erased evidence');
  assert.ok(report.blockers.includes('rawMidiSource'));
  assert.notEqual(report.state, 'VALIDATED');
});

test('an edited stored project cannot pass itself off as these bytes', () => {
  const result = asset('zero.mid', fixtures.format0());
  const edited = structuredClone(result);
  // Same bytes, same digest, one pitch quietly changed in the stored project.
  edited.project.events[0].pitch = 61;

  let workspace = { ...newWorkspace(), title: 'fixture', settings: { meterText: '0 4/4', recording: 'synthetic', offset: '0', end: '2', audioRequired: 'no', preview: 'none' } };
  workspace.assets.candidate = edited;
  const entry = analyzeWorkspace(workspace).rawMidi[0];
  assert.equal(entry.integrity.verified, false);
  assert.ok(entry.integrity.reasons.includes('STORED_PROJECT_DOES_NOT_MATCH_SOURCE_BYTES'));
});

test('an incomplete Raw MIDI project stays incomplete through a merge, whatever the caller claims', () => {
  const damaged = asset('truncated.mid', fixtures.truncatedTrack());
  assert.equal(damaged.project.metadata.sourceComplete, false);

  const merged = mergeCanonicalProjects([damaged.project], {
    id: 'merged',
    // PR #20: caller metadata is annotation and is spread first; what the merge
    // computed is written after it and is not overridable.
    metadata: { sourceComplete: true, incompleteInputs: [], componentProjects: [] },
  });
  assert.equal(merged.metadata.sourceComplete, false);
  assert.deepEqual(merged.metadata.incompleteInputs, [damaged.project.id]);
  assert.equal(merged.metadata.componentProjects.length, 1);
});

test('a tampered persisted record cannot claim a source identity it does not have', () => {
  const result = asset('zero.mid', fixtures.format0());
  for (const [mutate, reason] of [
    [record => { record.source.sha256 = '0'.repeat(64); }, 'SOURCE_DIGEST_MISMATCH'],
    [record => { record.source.byteLength = 3; }, 'SOURCE_BYTE_LENGTH_MISMATCH'],
    [record => { record.project.sources[0].sha256 = '1'.repeat(64); }, 'CANONICAL_SOURCE_DIGEST_MISMATCH'],
    [record => { record.source.bytesBase64 = encodeSourceBytes(fixtures.format1()); }, 'SOURCE_DIGEST_MISMATCH'],
    [record => { delete record.source.bytesBase64; }, 'SOURCE_BYTES_MISSING'],
  ]) {
    const record = structuredClone(result);
    mutate(record);
    const verdict = verifySourceBytes(record);
    assert.equal(verdict.verified, false);
    assert.ok(verdict.reasons.includes(reason), `${reason} must be reported, got ${verdict.reasons.join(',')}`);
  }
});

// ─── percussion ─────────────────────────────────────────────────────────────

test('channel 10 note numbers never become pitched Canonical notes', () => {
  const result = asset('drums.mid', fixtures.percussion());
  assert.equal(result.complete, false);
  assert.equal(result.project.events.length, 2, 'only the pitched track produces note events');
  for (const event of result.project.events) assert.equal(event.metadata.channel, 0);

  const percussion = result.unsupported.filter(item => item.code === 'PERCUSSION_CHANNEL_EVENT');
  assert.equal(percussion.length, 3);
  assert.equal(result.midi.percussionEventCount, 3);
  assert.deepEqual(result.midi.percussionChannels, [9]);
  assert.deepEqual(result.midi.percussionNoteNumbers, [36, 38, 42]);
  // The drum note numbers must not appear as pitches anywhere in the project.
  const pitches = new Set(result.project.events.map(event => event.pitch));
  for (const number of [36, 38, 42]) assert.equal(pitches.has(number), false);
  // And full timing is retained so an evidence-backed mapping stays possible.
  for (const item of percussion) assert.ok(Number.isInteger(item.startTick) && Number.isInteger(item.endTick));
});

// ─── source authority ───────────────────────────────────────────────────────

test('a Raw MIDI source is supporting evidence unless the caller claims otherwise', () => {
  const third = asset('third.mid', fixtures.format0());
  assert.equal(third.source.kind, 'third-party-midi');
  assert.equal(third.source.authority, 'supporting');
  assert.equal(third.project.sources[0].authority, 'supporting');

  const official = asset('official.mid', fixtures.format0(), { authority: 'primary-symbolic' });
  assert.equal(official.source.kind, 'official-midi');
  assert.equal(official.source.authority, 'primary-symbolic');
  // The claim changes the source record only; it never repairs completeness.
  const damaged = asset('damaged.mid', fixtures.truncatedTrack(), { authority: 'primary-symbolic' });
  assert.equal(damaged.complete, false);
});

// ─── routing and asset shape ────────────────────────────────────────────────

test('the file extension is a hint; the header bytes are what route the file', () => {
  assert.equal(looksLikeMidi(fixtures.format0()), true);
  assert.equal(looksLikeMidi(fixtures.notMidiAtAll()), false);
  assert.equal(looksLikeMidi(new Uint8Array([0x4d, 0x54])), false);
  assert.equal(looksLikeMidi(new TextEncoder().encode('MML@t120o4c1,,,,,;')), false);
  assert.equal(looksLikeMidi(null), false);
});

test('a Raw MIDI asset is recognisable and never mistaken for a text asset', () => {
  const midi = asset('a.mid', fixtures.format0());
  assert.equal(midi.format, MIDI_SOURCE_FORMAT);
  assert.equal(isRawMidiAsset(midi), true);
  assert.equal(midi.content, undefined, 'there is no text representation of the source');

  const mml = intake({ name: 'a.mml', content: 'MML@t120o4c1,,,,,;', id: 'mml', meterText: '0 4/4' });
  assert.equal(isRawMidiAsset(mml), false);
  assert.equal(mml.format, 'MML');
});

// ─── request identity ───────────────────────────────────────────────────────

test('only the newest request for a slot may become the active source', () => {
  const ledger = createSourceRequestLedger();
  const a = ledger.begin('candidate', { projectId: 'p1', revision: 0 });
  const b = ledger.begin('candidate', { projectId: 'p1', revision: 0 });

  // A returns late; B is what the user last chose.
  assert.deepEqual(ledger.evaluate(a, { projectId: 'p1' }), { accepted: false, reason: STALE_SOURCE_REQUEST });
  assert.deepEqual(ledger.evaluate(b, { projectId: 'p1' }), { accepted: true, reason: null });

  // Identical filenames are not identity: two requests are two requests.
  assert.notEqual(a.sequence, b.sequence);

  // Another slot is unaffected by the candidate slot's traffic.
  const other = ledger.begin('baseline', { projectId: 'p1' });
  assert.equal(ledger.evaluate(other, { projectId: 'p1' }).accepted, true);

  // Navigating to another project discards results requested against the old one.
  assert.deepEqual(ledger.evaluate(b, { projectId: 'p2' }), { accepted: false, reason: SOURCE_REQUEST_PROJECT_CHANGED });

  ledger.settle(b);
  assert.deepEqual(ledger.evaluate(b, { projectId: 'p1' }), { accepted: false, reason: STALE_SOURCE_REQUEST });
});

test('an intake stays valid across revisions of the same project', () => {
  const ledger = createSourceRequestLedger();
  const token = ledger.begin('candidate', { projectId: 'p1', revision: 3 });
  // The workspace revision moved while the decode was in flight; the captured
  // bytes are still the user's choice and still invalidate on their own.
  assert.equal(ledger.evaluate(token, { projectId: 'p1' }).accepted, true);
  assert.deepEqual(ledger.inFlight, [{ slot: 'candidate', sequence: token.sequence, projectId: 'p1', revision: 3 }]);
});

// ─── worker dispatch ────────────────────────────────────────────────────────

test('the analysis Worker dispatches intakeMidi and nothing outside its allowlist', async () => {
  const source = await readFile(new URL('../web/worker.mjs', import.meta.url), 'utf8');
  const list = source.match(/\[((?:'[a-zA-Z]+',?\s*)+)\]\.includes\(data\.action\)/);
  assert.ok(list, 'the Worker must keep an explicit action allowlist');
  const actions = list[1].split(',').map(item => item.trim().replace(/'/g, '')).filter(Boolean);
  assert.ok(actions.includes('intakeMidi'));
  assert.ok(actions.includes('intake'), 'the existing symbolic intake stays reachable');
  const model = await import('../web/model.mjs');
  for (const action of actions) assert.equal(typeof model[action], 'function', `${action} must exist on the model`);
});

// ─── existing source types stay compatible ──────────────────────────────────

test('MML, MusicXML and Canonical IR intake are unchanged by the MIDI path', () => {
  const mml = intake({ name: 'a.mml', content: 'MML@t120o4c1,t120o3e1,t120o2c1,,,;', id: 'mml', meterText: '0 4/4' });
  assert.equal(mml.format, 'MML');
  assert.equal(mml.complete, true);

  const xml = intake({ name: 'a.musicxml', id: 'xml', content: '<score-partwise><part-list><score-part id="P1"><part-name>P</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration></note></measure></part></score-partwise>' });
  assert.equal(xml.format, 'MusicXML');

  const ir = intake({ name: 'a.json', content: JSON.stringify(mml.project), id: 'ir' });
  assert.equal(ir.format, 'Canonical IR');
});

test('a workspace can mix a Raw MIDI candidate with a symbolic baseline', () => {
  let workspace = { ...newWorkspace(), title: 'mixed', settings: { meterText: '0 4/4', recording: 'synthetic', offset: '0', end: '2', audioRequired: 'no', preview: 'none' } };
  workspace.assets.candidate = asset('candidate.mid', fixtures.format0(), { id: 'midi-candidate' });
  workspace.assets.baseline = intake({ name: 'baseline.mml', content: 'MML@t120o4c1,t120o3e1,t120o2c1,,,;', id: 'baseline', meterText: '0 4/4' });
  const report = analyzeWorkspace(workspace);
  assert.equal(report.rawMidi.length, 1);
  assert.equal(report.rawMidi[0].slot, 'candidate');
  assert.equal(report.gates.rawMidiSource.status, 'PASS');
  assert.equal(report.gates.rawMidiSource.reason, 'RAW_MIDI_BYTES_MATCH_SOURCE_IDENTITY');
  // Byte identity is not source approval: that gate is still its own review.
  assert.equal(report.gates.source.status, 'PENDING');
  assert.equal(report.state, 'CANDIDATE');
});

test('a portable backup carries the MIDI bytes and re-ingests from them', () => {
  const workspace = newWorkspace();
  workspace.assets.candidate = asset('backup.mid', fixtures.format1(), { id: 'original' });
  const backup = JSON.stringify(workspace);
  const restored = importWorkspace(backup);

  const before = workspace.assets.candidate;
  const after = restored.assets.candidate;
  assert.equal(after.format, MIDI_SOURCE_FORMAT);
  assert.equal(after.source.sha256, before.source.sha256);
  assert.deepEqual([...decodeSourceBytes(after.source.bytesBase64)], [...fixtures.format1()]);
  assert.equal(after.project.events.length, before.project.events.length);
  assert.equal(verifySourceBytes(after).verified, true);

  // A backup whose bytes and claimed identity disagree is refused outright.
  const tampered = JSON.parse(backup);
  tampered.assets.candidate.source.bytesBase64 = encodeSourceBytes(fixtures.format0());
  assert.throws(() => importWorkspace(JSON.stringify(tampered)), /SOURCE_DIGEST_MISMATCH/);

  // And one whose project was edited is rebuilt from the bytes regardless.
  const edited = JSON.parse(backup);
  edited.assets.candidate.project.events = [];
  edited.assets.candidate.complete = true;
  const rebuilt = importWorkspace(JSON.stringify(edited));
  assert.equal(rebuilt.assets.candidate.project.events.length, before.project.events.length);
});

test('changing the source clears every review the old bytes were judged under', () => {
  let workspace = { ...newWorkspace(), title: 'fixture', settings: { meterText: '0 4/4', recording: 'synthetic', offset: '0', end: '2', audioRequired: 'no', preview: 'none' } };
  workspace.assets.candidate = asset('same-name.mid', fixtures.format0(), { id: 'first' });
  workspace = recordReview(workspace, 'source', 'checked', 'synthetic');
  assert.equal(workspace.reviews.source.revision, workspace.revision);

  const next = invalidate(workspace);
  // Same filename, different bytes: a new source revision, not the old one.
  next.assets.candidate = asset('same-name.mid', fixtures.format1(), { id: 'second' });
  assert.notEqual(next.assets.candidate.source.sha256, workspace.assets.candidate.source.sha256);
  assert.equal(next.revision, workspace.revision + 1);
  assert.deepEqual(next.reviews, {});
});
