import test from 'node:test';
import assert from 'node:assert/strict';
import {F,DEMO,ROLES,validateMML,parseTrack,parseMeter,buildBars,writeMidi,readMidi,compareMidi,writeABC,readABC,secondsAt} from '../dist/core.js';
const settings={meterText:'0 4/4\n8 2/4\n10 4/4'};
const demo=()=>{const r=validateMML(DEMO,settings);assert.equal(r.ok,true,JSON.stringify(r.errors));return r.song};
const six=raw=>'MML@'+Array(6).fill(raw).join(',')+';';
const load=(raw,options={})=>{const r=validateMML(six(raw),options);assert.equal(r.ok,true,JSON.stringify(r.errors));return r.song};
test('source fractions are exact',()=>{assert.equal(new F('1/3').add('1/6').toString(),'1/2');assert.equal(new F('0.125').toString(),'1/8')});
test('mixed meter retains internal 2/4 at beat 8',()=>{const s=demo();assert.equal(s.total,'18');assert.deepEqual(s.bars.map(b=>b.end),['4','8','10','14','18']);assert.equal(s.tempo[1].beat,'8')});
test('SMF and expanded ABC independently decode identical notes and settings',()=>{const s=demo();for(const model of [readMidi(writeMidi(s)),readABC(writeABC(s),settings)])assert.deepEqual(compareMidi(s,model),{ok:true,errors:[]})});
for(const raw of ['t120o4c3.','t120o4c6.','t120o4c12.','t120o4c24.','t120o4c48','t120o4c64','t120o4c128','t120o4r64','t120o4l64c','t120o4c0','t120o4c4..'])test('strict rejection: '+raw,()=>assert.ok(parseTrack(raw,'Melody').errors.length));
for(const raw of ['t120o4r1.&d2&d8','t120o4c4&r4','t120o4c4&d4','t120o4c4&&c4','t120o4c4&','t120c4','t120o4n60'])test('encoding rejection: '+raw,()=>assert.ok(parseTrack(raw,'Melody').errors.length));
test('same-pitch tie merges sound but preserves volume change inside sustain',()=>{const s=load('t120o4v8c4&v1c4r2');assert.equal(s.tracks[0].events.length,1);assert.equal(s.tracks[0].events[0].end,'2');assert.deepEqual(s.tracks[0].controls.map(x=>[x.beat,x.value]),[['0',8],['1',1]]);assert.ok(compareMidi(s,readMidi(writeMidi(s))).ok);assert.ok(compareMidi(s,readABC(writeABC(s))).ok)});
test('triplet without dotted shorthand remains exact',()=>{const s=load('t120o4l12cccccccccccc');assert.equal(s.total,'4');assert.ok(compareMidi(s,readABC(writeABC(s))).ok)});
test('natural rests and reattacks remain separate',()=>{const t=parseTrack('t120o4c8r8c8r8c2','Melody');assert.equal(t.events.length,3);assert.equal(t.events[1].start,'1');assert.equal(t.total,'4')});
test('missing track tempo fails',()=>{const r=validateMML('MML@t120o4c1,o4c1,,,,;');assert.equal(r.ok,false)});
test('empty logical tracks survive all exports',()=>{const r=validateMML('MML@t120o4c1,,,,,;');assert.equal(r.ok,true);assert.equal(readMidi(writeMidi(r.song)).tracks.length,7);assert.ok(compareMidi(r.song,readABC(writeABC(r.song))).ok)});
test('no implicit padding for final partial bars',()=>{assert.equal(validateMML(six('t120o4c1c2')).ok,false);const s=load('t120o4c1c2',{finalPartial:'2'});assert.equal(s.total,'6');assert.ok(compareMidi(s,readABC(writeABC(s),{finalPartial:'2'})).ok)});
test('pickup and final partial preserve correct bar structure',()=>{const s=load('t120o4c4c1c2.',{pickup:'1',finalPartial:'3'});assert.deepEqual(s.bars.map(x=>x.end),['1','5','8']);assert.ok(compareMidi(s,readABC(writeABC(s),{pickup:'1',finalPartial:'3'})).ok)});
test('misplaced meter change blocked instead of rewriting notes',()=>assert.throws(()=>buildBars('12',parseMeter('0 4/4\n3 2/4')),/小節內/));
test('duplicated or missing middle-song tempo is rejected',()=>{assert.ok(parseTrack('t120t120o4c1','Melody').errors.length);const s=demo(),m=readMidi(writeMidi(s));m.tempo.pop();assert.equal(compareMidi(s,m).ok,false)});
test('bad MIDI volume is caught even when counts and hashes could match',()=>{const s=demo(),bytes=writeMidi(s);let changes=0;for(let i=0;i<bytes.length-2;i++)if((bytes[i]&240)===176&&bytes[i+1]===7){bytes[i+2]=0;changes++}assert.equal(changes,6);const c=compareMidi(s,readMidi(bytes));assert.equal(c.ok,false);assert.ok(c.errors.some(x=>x.includes('音量')))});
test('wrong MIDI program caught',()=>{const s=demo(),bytes=writeMidi(s);for(let i=0;i<bytes.length-1;i++)if(bytes[i]===192){bytes[i+1]=40;break}assert.ok(compareMidi(s,readMidi(bytes)).errors.some(x=>x.includes('Program')))});
test('wrong MIDI meter caught',()=>{const s=demo(),bytes=writeMidi(s);for(let i=0;i<bytes.length-5;i++)if(bytes[i]===255&&bytes[i+1]===88){bytes[i+3]=3;break}assert.ok(compareMidi(s,readMidi(bytes)).errors.some(x=>x.includes('拍號')))});
test('engine event pitch mutation cannot hide behind same note count',()=>{const s=demo(),model=readMidi(writeMidi(s));model.tracks[1].events[0].pitch+=12;assert.ok(compareMidi(s,model).errors.some(x=>x.includes('音高')))});
test('velocity, end duration and channels checked',()=>{const s=demo();for(const mutate of [m=>m.tracks[1].events[0].velocity=1,m=>m.tracks[1].events[0].end='1/2',m=>m.tracks[1].channel=9]){const m=readMidi(writeMidi(s));mutate(m);assert.equal(compareMidi(s,m).ok,false)}});
test('mapped drum faces keep event identity and channel 10',()=>{const r=validateMML(six('t120o4c1'),{drumText:JSON.stringify({role:'Chord5',instrument:'Jazz Drum',evidence:'synthetic mapping, not game evidence',mapping:{60:36}})});assert.equal(r.ok,true);const model=readMidi(writeMidi(r.song));assert.equal(model.tracks[6].channel,9);assert.equal(model.tracks[6].events[0].pitch,36);assert.ok(compareMidi(r.song,model).ok);assert.ok(compareMidi(r.song,readABC(writeABC(r.song))).ok)});
test('incomplete or unsubstantiated drum profile fails',()=>{for(const drumText of ['{}','{"role":"Chord5","instrument":"Jazz Drum","evidence":"","mapping":{"60":36}}'])assert.equal(validateMML(six('t120o4c1'),{drumText}).ok,false)});
test('all 15 pairs retained without a 12-event sample cap',()=>{const s=load('t120o4l16'+'c'.repeat(32));assert.equal(s.review.pairs.length,15);assert.equal(s.review.pairs[0].overlaps.length,32);assert.equal(s.review.maxSimultaneousAttacks,6)});
test('same-source six-way attack is a review item rather than hard failure',()=>assert.equal(validateMML(six('t120o4c1')).ok,true));
test('tempo integral uses every segment',()=>{assert.ok(Math.abs(secondsAt('646',[{beat:'0',bpm:87},{beat:'38',bpm:138}])-290.55472263868)<1e-8)});
test('terminal control and tempo are retained without adding time',()=>{const s=load('t120o4c1v1t138');assert.equal(s.total,'4');assert.ok(compareMidi(s,readABC(writeABC(s))).ok)});
test('cross-bar tie never turns into extra attacks',()=>{const s=load('t120o4c1&c1');const text=writeABC(s);assert.ok(text.includes('=C4- |'));const model=readABC(text);assert.equal(model.tracks[1].events.length,1);assert.equal(model.tracks[1].events[0].end,'8')});
test('malformed MIDI fails closed',()=>{assert.throws(()=>readMidi(new Uint8Array([1,2,3])));const b=writeMidi(demo());assert.throws(()=>readMidi(b.slice(0,-1)))});
