import test from 'node:test';
import assert from 'node:assert/strict';
import {Player} from '../dist/player.js';
import {DEMO,validateMML,writeMidi,compareMidi,sha256} from '../dist/core.js';
const song=()=>validateMML(DEMO,{meterText:'0 4/4\n8 2/4\n10 4/4'}).song;
const param=()=>({value:0,events:[],setValueAtTime(v,t){this.events.push([v,t])},linearRampToValueAtTime(v,t){this.events.push([v,t])}});
class FakeContext{constructor(){this.currentTime=0;this.state='suspended';this.sampleRate=44100;this.destination={};this.started=[]}async resume(){this.state='running'}createGain(){return {gain:param(),connect(){},disconnect(){}}}createOscillator(){const c=this;return {frequency:param(),connect(){},disconnect(){},start(t){c.started.push(t)},stop(){}}}createBiquadFilter(){return {frequency:param(),connect(){}}}createBuffer(n,len,sr){return {duration:len/sr,getChannelData:()=>new Float32Array(len)}}createBufferSource(){return {connect(){},disconnect(){},start(){},stop(){}}}}
test('load capture decoded from bytes matches source and binds real input hash',async()=>{const s=song(),m=writeMidi(s),p=new Player();await p.load(m);const c=p.capture();assert.ok(compareMidi(s,c.effectiveModel).ok);assert.equal(c.midiSha256,await sha256(m));assert.equal(c.transport.audioContextState,'not_started');assert.equal(c.scope,'loaded_engine_and_scheduler_not_hardware_audio')});
test('callers cannot alter internal loaded state via mutable snapshot',async()=>{const s=song(),p=new Player();await p.load(writeMidi(s));const c=p.capture();c.effectiveModel.tracks[1].events[0].pitch=1;assert.ok(compareMidi(s,p.capture().effectiveModel).ok)});
test('source model is not copied back over corrupted loaded MIDI',async()=>{const s=song(),bytes=writeMidi(s);for(let i=0;i<bytes.length-2;i++)if(bytes[i]===176&&bytes[i+1]===7){bytes[i+2]=0;break}const p=new Player();await p.load(bytes);assert.equal(compareMidi(s,p.capture().effectiveModel).ok,false)});
test('synthetic context schedules only lookahead window and rebuilds sustain on seek',async()=>{const s=song(),c=new FakeContext(),p=new Player({contextFactory:()=>c});await p.load(writeMidi(s));await p.seek(.25);await p.play();const cap=p.capture();assert.equal(cap.transport.audioContextState,'running');assert.ok(cap.scheduledEvents.length>0);assert.ok(cap.scheduledEvents.length<37);assert.ok(cap.scheduledEvents.some(x=>x.resumedSustain));assert.ok(c.started.length>0);p.stop()});
test('mix readback lists actual selected core and mute state',async()=>{const p=new Player();await p.load(writeMidi(song()));p.setMix({layer:3,muted:new Set([1]),solo:null,volume:.3});const c=p.capture();assert.deepEqual(c.routing.activeRoles,['Melody','Chord2']);assert.equal(c.routing.masterVolume,.3)});
test('invalid loops do not silently clamp musical timeline',async()=>{const p=new Player();await p.load(writeMidi(song()));assert.throws(()=>p.setLoop(5,3,true));assert.throws(()=>p.setLoop(0,19,true));p.setLoop(8,10,true);assert.ok(p.loop.end>p.loop.start)});
