// Entry of the native core bundle (scripts/build-native-core.mjs).
//
// The host globals come first: modules evaluate in import order, and
// dist/core.js constructs a TextEncoder while it evaluates. `mml-native:build`
// is generated by the build and carries only the runtime package digest, so the
// bundle's bytes do not move with Git history.
import { INSTALLED_HOST_SHIMS } from './host-globals.mjs';
import { createNativeCore } from './core-facade.mjs';
import { NATIVE_BUILD } from 'mml-native:build';

globalThis.MMLNativeCore = createNativeCore({
  expectedCanonicalDigest: NATIVE_BUILD.canonicalDigest,
  hostShims: INSTALLED_HOST_SHIMS,
});
